# Generated by Django 3.1.7 on 2021-07-21 01:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.departments')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('designation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'EmployeeGroup',
                'verbose_name_plural': 'EmployeeGroups',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('Apprentice', 'Apprentice'), ('Intern', 'Intern'), ('Piecework', 'Piecework'), ('Commision', 'Commision'), ('Contract', 'Contract'), ('Probation', 'Probation'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], default='Full-Time', max_length=50)),
                ('gender', models.CharField(choices=[('Prefer not to say', 'Prefer not to say'), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], default='Prefer not to say', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField(default=datetime.date.today)),
                ('date_of_leaving', models.DateField(default=datetime.date.today)),
                ('date_of_retirement', models.DateField(default=datetime.date.today)),
                ('contact_no', models.CharField(max_length=15)),
                ('personal_email', models.EmailField(max_length=254)),
                ('company_email', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=200)),
                ('is_current_address_permanent', models.BooleanField(default=True)),
                ('permanent_address', models.CharField(max_length=200)),
                ('identification_document', models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('VoterID', 'VoterID')], default='PAN Card', max_length=30)),
                ('identification_number', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.departments')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.designations')),
                ('employee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeegroup')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.employees')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='LeavePolicies',
            fields=[
                ('leavepolicy_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'LeavePolicy',
                'verbose_name_plural': 'LeavePolicies',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('include_holidays_as_leaves', models.BooleanField(default=False)),
                ('is_compensatory', models.BooleanField(default=False)),
                ('allow_encashment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReports',
            fields=[
                ('monthlyreport_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_time_worked', models.FloatField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='LeavesApplications',
            fields=[
                ('leaveapplication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Open', max_length=50)),
                ('post_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employees')),
                ('leave_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approver', to='employees.employees')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavetype')),
            ],
            options={
                'verbose_name': 'LeaveApplication',
                'verbose_name_plural': 'LeaveApplications',
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_leave', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReport_Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_taken', models.IntegerField()),
                ('leaves_remaining', models.IntegerField()),
                ('blocked_till', models.DateField()),
                ('is_compulsory', models.BooleanField(default=False)),
                ('employee_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeeleavereport')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy_TypeMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days_allowed', models.IntegerField(default=0)),
                ('total_consecutive_days', models.IntegerField(default=0)),
                ('leave_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavepolicies')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavetype')),
            ],
        ),
        migrations.AddField(
            model_name='leavepolicies',
            name='leave_type',
            field=models.ManyToManyField(blank=True, null=True, through='employees.LeavePolicy_TypeMembership', to='employees.LeaveType'),
        ),
        migrations.AddField(
            model_name='employeeleavereport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='employeeleavereport',
            name='leave_types',
            field=models.ManyToManyField(to='employees.LeaveType'),
        ),
        migrations.CreateModel(
            name='EmployeeCheckins',
            fields=[
                ('check_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('checked_in', models.DateTimeField()),
                ('checked_out', models.DateTimeField(blank=True, null=True)),
                ('total_time_elapsed', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'verbose_name': 'EmployeeCheckin',
                'verbose_name_plural': 'EmployeeCheckins',
            },
        ),
        migrations.AddField(
            model_name='designations',
            name='leavepolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.leavepolicies'),
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('late_entry', models.BooleanField(default=False)),
                ('early_exit', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('total_time', models.FloatField(default=0.0)),
                ('checks', models.ManyToManyField(to='employees.EmployeeCheckins')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
