# Generated by Django 3.1.7 on 2021-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavepolicies',
            options={'verbose_name': 'Leave Policy', 'verbose_name_plural': 'Leave Policies'},
        ),
        migrations.AddField(
            model_name='attendances',
            name='total_overtime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employeecheckins',
            name='is_last_session',
            field=models.BooleanField(default=False),
        ),
    ]
