# Generated by Django 3.1.7 on 2021-08-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='date_of_leave',
            new_name='leave_date',
        ),
        migrations.AddField(
            model_name='employeesession',
            name='is_flagged_session',
            field=models.BooleanField(default=False),
        ),
    ]
