# Generated by Django 3.1.7 on 2021-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fk_employee_group',
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='fk_employee',
            field=models.ManyToManyField(to='employees.Employee'),
        ),
    ]
