# Generated by Django 3.1.7 on 2021-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeecheckins_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecheckins',
            name='total_time_elapsed',
            field=models.FloatField(blank=True),
        ),
    ]
