# Generated by Django 3.1.7 on 2021-07-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210722_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecheckins',
            name='is_first_session',
            field=models.BooleanField(default=False),
        ),
    ]
