# Generated by Django 3.1.7 on 2021-07-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeecheckins_is_first_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecheckins',
            name='date',
        ),
    ]
