# Generated by Django 3.1.7 on 2021-07-08 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210707_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecheckins',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
