# Generated by Django 3.1.7 on 2021-07-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeecheckins_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecheckins',
            old_name='employees',
            new_name='employee',
        ),
    ]
