# Generated by Django 3.1.7 on 2021-07-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employeecheckins_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_work_hours', models.FloatField(default=8)),
                ('workday_start_time', models.TimeField()),
                ('workday_end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='leavepolicies',
            name='is_half_day_leave',
            field=models.BooleanField(default=False),
        ),
    ]
