# Generated by Django 3.1.7 on 2021-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210708_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecheckins',
            name='total_time_elapsed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
