# Generated by Django 3.1.7 on 2021-07-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210723_0718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
        migrations.AddField(
            model_name='designations',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.schedules'),
        ),
    ]
