# Generated by Django 3.1.7 on 2021-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210708_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecheckins',
            name='checked_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
