# Generated by Django 3.1.7 on 2021-07-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210708_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesapplications',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Open', max_length=50),
        ),
    ]
