# Generated by Django 3.1.7 on 2021-07-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_leavesapplications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MonthlyReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_worked', models.FloatField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
    ]
