# Generated by Django 3.1.7 on 2021-07-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20210710_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('leave_types', models.ManyToManyField(to='employees.LeaveType')),
            ],
        ),
        migrations.RenameModel(
            old_name='Leave',
            new_name='Leaves',
        ),
        migrations.CreateModel(
            name='LeaveReport_Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_taken', models.IntegerField()),
                ('leaves_remaining', models.IntegerField()),
                ('blocked_till', models.DateField()),
                ('is_compulsory', models.BooleanField(default=False)),
                ('employee_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeeleavereport')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavetype')),
            ],
        ),
    ]
